# Install build dependencies
RUN apt-get update -y && apt-get install -y --no-install-recommends \
    ros-foxy-fog-msgs \
    ros-foxy-octomap \
    ros-foxy-octomap-msgs \
    ros-foxy-laser-geometry \
    ros-foxy-pcl-conversions \
    ros-foxy-pcl-msgs \
    && rm -rf /var/lib/apt/lists/*

ENV ROS=1
