RUN apt-get update -y && apt-get install -y --no-install-recommends \
    nlohmann-json3-dev \
    ros-foxy-geodesy \
    liblapacke-dev \
    libopenblas-dev \
    libatlas-base-dev \
    libsurvive \
    ros-foxy-px4-msgs \
    && rm -rf /var/lib/apt/lists/*

ENV ROS=1
