RUN apt-get update -y && apt-get install -y --no-install-recommends \
    golang \
    libgstreamer1.0-0 \
    libgstreamer-plugins-base1.0-dev \
    libgstreamer-plugins-bad1.0-dev \
    libgstreamer-plugins-good1.0-dev \
    ros-foxy-px4-msgs \
    && rm -rf /var/lib/apt/lists/*
