RUN apt-get update -y && apt-get install -y --no-install-recommends \
    ros-foxy-geodesy \
    ros-foxy-std-msgs \
    libasound-dev \
    portaudio19-dev \ 
    libportaudio2 \ 
    libportaudiocpp0 \
    python3-numpy \
    python3-pyaudio \
    python3-usb \
    && rm -rf /var/lib/apt/lists/*

ENV ROS=1
