ENV DEBIAN_FRONTEND="noninteractive" TZ="Europe/Helsinki"

RUN apt-get update -y && apt-get install -y --install-recommends \
    kernel-package \
    libncurses-dev \
    gawk \
    flex \
    bison \
    openssl \
    libssl-dev \
    dkms \
    libelf-dev \
    libudev-dev \
    libpci-dev \
    libiberty-dev \
    autoconf \
    git \
    gcc-9-plugin-dev \
    && rm -rf /var/lib/apt/lists/*

RUN sed -i "s/# deb-src http\:\/\/archive\.ubuntu\.com\/ubuntu\/ focal main restricted/deb-src http:\/\/archive.ubuntu.com\/ubuntu\/ focal main restricted/g" /etc/apt/sources.list \
    && sed -i "s/# deb-src http\:\/\/archive\.ubuntu\.com\/ubuntu\/ focal-updates main restricted/deb-src http:\/\/archive.ubuntu.com\/ubuntu\/ focal-updates main restricted/g" /etc/apt/sources.list \
    && apt-get update -y

WORKDIR /build
RUN apt-get source linux-hwe-5.11-source-5.11.0
