RUN apt-get update -y && apt-get install -y --no-install-recommends \
    libusb-1.0-0-dev \
    libgstreamer1.0-0 \
    libgstreamer-plugins-base1.0-dev \
    libgstreamer-plugins-bad1.0-dev \
    libgstreamer-plugins-good1.0-dev \
    && rm -rf /var/lib/apt/lists/*

ENV ROS=1

