RUN apt-get update -y && apt-get install -y --no-install-recommends \
    libusb-1.0-0-dev \
    libgstreamer1.0-0 \
    libgstreamer-plugins-base1.0-dev \
    libgstreamer-plugins-bad1.0-dev \
    libgstreamer-plugins-good1.0-dev \
    libgstrtspserver-1.0-dev \
    libgstreamer-plugins-base1.0-0 \
    libgstreamer-plugins-good1.0-0 \
    gstreamer1.0-x \
    gstreamer1.0-rtsp \
    gstreamer1.0-tools \
    gstreamer1.0-vaapi \
    gstreamer1.0-plugins-base \
    gstreamer1.0-plugins-good \
    gstreamer1.0-plugins-bad \
    gstreamer1.0-plugins-ugly \
    gstreamer1.0-plugins-rtp \
    gstreamer1.0-plugins-base-apps \
    && rm -rf /var/lib/apt/lists/*

ENV ROS=1

ENV XDG_RUNTIME_DIR=/tmp
